Layout/HashAlignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/tasks/**/*
    - config/environments/*
    - config/routes.rb
    - Gemfile

Layout/LineLength:
  Max: 120

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - db/seeds/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
  